### ISSUE TITLE
error in install_zipline

### ISSUE THREAD

**Issue by autotrader2025** [DavisVaughan/flyingfox#2]
hi David,

thank you for the fantastic job. One quick question. you mention

To get started with zipline, you’ll need the zipline Python module. Install it with:
install_zipline()

i tried the following:

> library(flyingfox)
> install_zipline()
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

- zipline

Current channels:

- https://conda.anaconda.org/...
- https://conda.anaconda.org/...
- https://repo.anaconda.com/p...
- https://repo.anaconda.com/p...
- https://repo.anaconda.com/p...
- https://repo.anaconda.com/p...
- https://repo.anaconda.com/p...
- https://repo.anaconda.com/p...
- https://repo.anaconda.com/p...
- https://repo.anaconda.com/p...
- https://repo.anaconda.com/p...
- https://repo.anaconda.com/p...

however, install zipline in anaconda worked.

here is anaconda info:

(base) C:\Windows\system32>conda info

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\mark\.condarc
 populated config files : C:\Users\mark\.condarc
          conda version : 4.5.4
    conda-build version : 3.10.9
         python version : 3.5.5.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/Qantopian/win-64
                          https://conda.anaconda.org/Qantopian/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\mark\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\mark\AppData\Local\conda\conda\envs
                          C:\Users\mark\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.19.1 CPython/3.5.5 Windows/7 Wi
ndows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False

(base) C:\Windows\system32>

**Comment by zhaimac** [comment]
library(flyingfox)
install_zipline()

Works well on python2.  However, for python3.5 I have to manually create the conda environment. After conda zipline env created everything works as expected.

**Comment by autotrader2025** [comment]
Hi Zhai,

Thank you for the reply.  I am beginner of python and R.  so, it is difficult for me to find out a correct way to install zipline in RStudio.


in anaconda,  if i ran "conda install zipline", it failed with the same reason like zipline not found.

however, if i added the correct channel for zipline to conda config, like

conda config --prepend channels https://conda.anaconda.org/quantopian

then, ran "conda install zipline", it worked.  ( ran "conda install -c quantopian zipline" always works)

do you know how to add channel to conda config in RStudio?

(FYI:
1) i tried install python2 with anaconda 5.2, could not find zipline when ran install_zipline in RStudio.
2) I tried install anaconda 4.2 with python 3.5, then in conda command prompt, i make a new env for zipline as follow:
conda create -n env_zipline python=3.5
activate env_zipline
then ran install_zipline in RStudio, no luck, still got zipline not found
)

**Comment by autotrader2025** [comment]
here are the result that I  tried to install zipline in RStudio in windows 10 ( I used windows 7 previously) after reinstall R 3.5, RStudio 1.1.447 and created env_zipline in conda prompt

Fetching package metadata ...........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current win-64 channels: 
  - zipline

You can search for packages on anaconda.org with

    anaconda search -t conda zipline


Error: Error 1 occurred installing packages into conda environment r-reticulate

**Comment by autotrader2025** [comment]
I think i found the way. After install zipline using "conda install -c quantopian zipline" in conda prompt (creating an isolated env called env_zipline and install zipline in it).  Thanks.

> library(reticulate)
> library(flyingfox)
> conda_list()
          name                                                     python
1  env_zipline  C:\\Users\\Mark\\Anaconda3\\envs\\env_zipline\\python.exe
2 r-reticulate C:\\Users\\Mark\\Anaconda3\\envs\\r-reticulate\\python.exe
> use_condaenv("env_zipline")
> fly_ingest()
Downloading WIKI Prices table from Quandl

**Comment by zhaimac** [comment]
Thanks for sharing this. I tested the conda install approach. It works.

**Comment by englianhu** [comment]
```diff
> devtools::install_github('DavisVaughan/flyingfox')
> library(flyingfox)
> install_zipline()
Fetching package metadata ...............

PackageNotFoundError: Packages missing in current channels:
            
  - zipline

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
            

- Error: Error 1 occurred installing packages into conda environment r-reticulate
> conda_list()
          name                                                      python
1 r-reticulate C:\\Users\\scibr\\Anaconda3\\envs\\r-reticulate\\python.exe
2 r-tensorflow C:\\Users\\scibr\\Anaconda3\\envs\\r-tensorflow\\python.exe
> use_condaenv("env_zipline")
> fly_ingest()
- Error: Please set your QUANDL_API_KEY as an environment variable in your .Renviron file. An easy way to do this is with usethis::edit_r_environ().
```

**Comment by englianhu** [comment]
https://github.com/quantopian/zipline/issues/2093#issuecomment-361082811
